export const countries = [
  { code: "BI", name: "Burundi" },
  { code: "KM", name: "Comoros" },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
  },
  { code: "DJ", name: "Djibouti" },
  { code: "EG", name: "Egypt" },
  { code: "ER", name: "Eritrea" },
  { code: "ET", name: "Ethiopia" },
  { code: "KE", name: "Kenya" },
  { code: "LY", name: "Libya" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MU", name: "Mauritius" },
  { code: "RW", name: "Rwanda" },
  { code: "SC", name: "Seychelles" },
  { code: "SD", name: "Sudan" },
  { code: "SZ", name: "Eswatini" },
  { code: "UG", name: "Uganda" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "SO", name: "Somalia" },
  { code: "TN", name: "Tunisia" },
];

export const countryRegions = [
  { region: "Bujumbura", name: "Burundi" },
  { region: "Grande Comore", name: "Comoros" },
  { region: "Kinshasa", name: "Democratic Republic of the Congo" },
  { region: "Djibouti City", name: "Djibouti" },
  { region: "Cairo", name: "Egypt" },
  { region: "Maekel", name: "Eritrea" },
  { region: "Addis Ababa", name: "Ethiopia" },
  { region: "Nairobi", name: "Kenya" },
  { region: "Tripoli", name: "Libya" },
  { region: "Analamanga", name: "Madagascar" },
  { region: "Lilongwe", name: "Malawi" },
  { region: "Port Louis", name: "Mauritius" },
  { region: "Kigali", name: "Rwanda" },
  { region: "Mahé", name: "Seychelles" },
  { region: "Khartoum", name: "Sudan" },
  { region: "Hhohho", name: "Eswatini" },
  { region: "Central", name: "Uganda" },
  { region: "Lusaka", name: "Zambia" },
  { region: "Harare", name: "Zimbabwe" },
  { region: "Banadir", name: "Somalia" },
  { region: "Tunis", name: "Tunisia" },
];
