export const productsData = [
  {
    id: 1,
    image:
      "https://i0.wp.com/foodieng.com/wp-content/uploads/2022/05/yellow-maiz.jpg?fit=1000%2C867&ssl=1",
    name: "Yellow Maize",
    type: "Cereal",
    country: "United States",
    region: "Midwest",
    cropVariety: "Pioneer P1197",
    totalOrder: 1234,
    price: "$180.50/ton",
    active: true,
  },
  {
    id: 2,
    image:
      "https://www.foodandwine.com/thmb/XbKXqQvF61Csj9XLs_Nj3xwlwEI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Everything-You-Need-To-Know-About-Arabica-Coffee-FT-BLOG0822-2000-127d1551916e45138ea373de75f08138.jpg",
    name: "Arabica Coffee",
    type: "Coffee",
    country: "Brazil",
    region: "Minas Gerais",
    cropVariety: "Bourbon",
    totalOrder: 2184,
    price: "$4.20/lb",
    active: true,
  },
  {
    id: 3,
    image:
      "https://www.fieldstoneorganics.ca/wp-content/uploads/2022/04/Hard-Red-Winter-Wheat.jpg",
    name: "Hard Red Wheat",
    type: "Cereal",
    country: "Canada",
    region: "Saskatchewan",
    cropVariety: "Red Fife",
    totalOrder: 1255,
    price: "$280.00/ton",
    active: true,
  },
  {
    id: 4,
    image: "https://www.scoular.com/wp-content/uploads/2020/10/soy-beans.jpg",
    name: "Soybeans",
    type: "Legume",
    country: "Argentina",
    region: "Pampas",
    cropVariety: "DM 4670",
    totalOrder: 921,
    price: "$520.00/ton",
    active: false,
  },
  {
    id: 5,
    image:
      "https://5.imimg.com/data5/SELLER/Default/2023/4/303834484/WA/YW/BS/59043273/basmati-rice.webp",
    name: "Basmati Rice",
    type: "Rice",
    country: "India",
    region: "Punjab",
    cropVariety: "Pusa-1121",
    totalOrder: 1522,
    price: "$1200.00/ton",
    active: true,
  },
];
